### ISSUE TITLE
Metrics without a timeseries are not reported with the `metricSinks.prometheusScrapingEndpoint.metricUnavailableValue`

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1197]
Metrics without a timeseries are not reported with the `metricSinks.prometheusScrapingEndpoint.metricUnavailableValue`

**Comment by tomkerkhove** [comment]
Example:
```
[19:03:15 FTL] Failed to scrape resource for metric 'azure_event_hubs_incoming_messages_discovery'
Promitor.Integrations.AzureMonitor.Exceptions.MetricInformationNotFoundException: No metric information was found for 'IncomingMessages'. Reason: 'No time series was found'
   at Promitor.Integrations.AzureMonitor.AzureMonitorClient.QueryMetricAsync(String metricName, String metricDimension, AggregationType aggregationType, TimeSpan aggregationInterval, String resourceId, String metricFilter) in C:\Code\GitHub\promitor\src\Promitor.Integrations.AzureMonitor\AzureMonitorClient.cs:line 88
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in C:\Code\GitHub\promitor\src\Promitor.Core.Scraping\AzureMonitorScraper.cs:line 46
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in C:\Code\GitHub\promitor\src\Promitor.Core.Scraping\Scraper.cs:line 69
```
