### ISSUE TITLE
ApplicationGateway metric dimension raise BadRequest error

### ISSUE THREAD

**Issue by Zeka13** [tomkerkhove/promitor#1425]
Hello! I am new with promitor and trying to configure **WAF V2 ApplicationGateway** metric with one dimension regarding https://promitor.io/configuration/v2.x/metrics/

**So my config is** 

```
version: v1
azureMetadata:
  tenantId: *****
  subscriptionId: *****
  resourceGroupName: my-production
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: azure_response_status
    description: "HTTP response status returned by Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: ResponseStatus
      dimension:
        name: HttpStatus
      aggregation:
        type: Total
    resources:
      - applicationGatewayName: k8s-appgw-11111111
```

**And I am installing promitor like this**
```
helm install promitor-agent-scraper promitor/promitor-agent-scraper --version v2.0.0-rc -n monitoring\
               --set azureAuthentication.appId="${appId}" \
               --set azureAuthentication.appKey="${password}" \
               --values metric-declaration.yaml
```

**Unfortunately dimension is not working and I am getting this error in logs**

```
[20:50:00 FTL] Failed to scrape resource for metric 'azure_response_status'
Microsoft.Azure.Management.Monitor.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.Fluent.MetricsOperations.ListWithHttpMessagesAsync(String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.Fluent.MetricsOperationsExtensions.ListAsync(IMetricsOperations operations, String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.Fluent.Models.MetricDefinitionImpl.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.Fluent.Models.MetricDefinitionImpl.Microsoft.Azure.Management.Monitor.Fluent.IWithMetricsQueryExecute.ExecuteAsync(CancellationToken cancellationToken)
   at Promitor.Integrations.AzureMonitor.AzureMonitorClient.GetRelevantMetric(String metricName, AggregationType metricAggregation, TimeSpan metricInterval, String metricFilter, String metricDimension, IMetricDefinition metricDefinition, DateTime recordDateTime) in /src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs:line 150
   at Promitor.Integrations.AzureMonitor.AzureMonitorClient.QueryMetricAsync(String metricName, String metricDimension, AggregationType aggregationType, TimeSpan aggregationInterval, String resourceId, String metricFilter) in /src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs:line 82
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 51
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 69
[20:50:00 FTL] Operation returned an invalid status code 'BadRequest'
```

without dimension sections promitor works the same way without any error in logs

What I am doing wrong? Thx in advance.

Btw I also tried all in lower case
```    
dimension:
      name: httpstatus
```
and use metricDimension instead of dimension, but no luck

**Comment by tomkerkhove** [comment]
It looks like the only supported dimension for it is `HttpStatusGroup` based on https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftnetworkapplicationgateways, can you give it a try please?

**Comment by tomkerkhove** [comment]
Thank you for using Promitor btw! 🙏

**Comment by Zeka13** [comment]
yes, this did the trick, thanks a lot. It was confusing that in Azure portral dismention name is HttpStatus and also promitor logs wasn't clear for me at this point. Maybe it is a good idea to add this useful  link you gave me to promitor docs.
