### ISSUE TITLE
Image is unable to resolve Prometheus service

### ISSUE THREAD

**Issue by ggustin** [tomkerkhove/promitor#1711]
### Report

Missing dependency in docker image `tomkerkhove/promitor-agent-scraper:latest-linux`

### Expected Behavior

The docker image to start.

### Actual Behavior

The execution stops because the type `Prometheus.Client.Abstractions.IMetricFactory` cannot be found.

### Steps to Reproduce the Problem

Launch a dockerized instance of Promitor with the following configuration

### Component

Scraper

### Version

2.0

### Configuration

Configuration:

```yaml
azureMetadata:
  tenantId:  "###########"
  subscriptionId: "###########"
  resourceGroupName: test-monitoring-platform
  scope: Global
server:
  httpPort: 8080
metricsConfiguration:
  absolutePath: /config/metrics-configuration.yml
```

### Logs

```shell
Aug 02 14:26:13 monitoring-platform docker[184792]: System.InvalidOperationException: Unable to resolve service for type 'Prometheus.Client.Abstractions.IMetricFactory' while attempting to activate 'Promitor.Integrations.Sinks.Prometheus.RuntimeMetricsCollector'.
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.DependencyInjection.SchedulingExtensions.ScheduleMetricScraping(IServiceCollection services) in /src/Promitor.Agents.Scraper/SchedulingExtensions.cs:line 34
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Promitor.Agents.Scraper.Startup.ConfigureServices(IServiceCollection services) in /src/Promitor.Agents.Scraper/Startup.cs:line 55
Aug 02 14:26:13 monitoring-platform docker[184792]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Microsoft.Extensions.Hosting.HostBuilder.Build()
Aug 02 14:26:13 monitoring-platform docker[184792]:    at Promitor.Agents.Scraper.Program.Main(String[] args) in /src/Promitor.Agents.Scraper/Program.cs:line 34
```

### Contact Details

gabriele.gustin@optionfactory.net

**Comment by tomkerkhove** [comment]
Sorry to see this! However, I don't see any metric sink being configured - Can you add one please?
https://promitor.io/configuration/v2.x/runtime/scraper#metric-sinks

Just so you know, there is a newer version of Promitor if you want to give it a go.

**Comment by ggustin** [comment]
Sure, here you go:
```
version: v1
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
runtime:
  metricSinks:
    prometheusScrapingEndpoint:
      enabled: true
      baseUriPath: /metrics
      enableMetricTimestamps: True
```

**Comment by tomkerkhove** [comment]
Note that you'll need to remove the runtime as this is not how it is configured:
https://promitor.io/configuration/v2.x/runtime/scraper

**Comment by ggustin** [comment]
Thank you very much. I got confused among all possible configurations

**Comment by tomkerkhove** [comment]
No problem, feel free to let me know what the outcome is.
