### ISSUE TITLE
AzureResourceGraph cannot initialize the Prometheus measurement due to empty label value

### ISSUE THREAD

**Issue by locmai** [tomkerkhove/promitor#1801]
### Report

I have a simple resource discovery that have been working with SystemAssignedManagedIdentity for a while with 0.4.1 version. After the system metrics introduced in 0.5.0, we have the error in the actual behavior session.

After investigate the issue, it looks like the `metricLabels` we defined here:
https://github.com/tomkerkhove/promitor/blob/b1b882b96813d67e81089922f124a75a74bc643f/src/Promitor.Agents.ResourceDiscovery/Graph/AzureResourceGraph.cs#L272-L278

So the dictionary contains the `"app_id" = _azureAuthenticationInfo.IdentityId` which the _azureAuthenticationInfo.IdentityId could be empty if we were using SystemAssignedManagedIdentity instead of UserAssignedManagedIdentity. 

We might fix this by using the similar one as DetermineApplicationId in here:
https://github.com/tomkerkhove/promitor/blob/b1b882b96813d67e81089922f124a75a74bc643f/src/Promitor.Integrations.AzureMonitor/RequestHandlers/AzureResourceManagerThrottlingRequestHandler.cs#L51-L58

I could pick this work up real quick if this was the true root cause.

### Expected Behavior

Should work normally when upgrading to 0.5.0

### Actual Behavior

I have the following error:

```
[17:19:51 FTL] Unhandled exception in job Azure Subscription Discovery
System.AggregateException: One or more errors occurred. (Label value cannot be empty)
 ---> System.ArgumentException: Label value cannot be empty
   at Prometheus.Client.LabelsHelper.GetHashCode(IReadOnlyList`1 values)
   at Prometheus.Client.MetricFamily`4.Prometheus.Client.IMetricFamily<TMetric>.WithLabels(String[] labels)
   at Promitor.Core.Metrics.Prometheus.Collectors.PrometheusMetricsCollector.WriteGaugeMeasurement(String name, String description, Double value, Dictionary`2 labels, Boolean includeTimestamp) in /src/Promitor.Core/Prometheus/Collectors/PrometheusMetricsCollector.cs:line 33
   at Promitor.Agents.ResourceDiscovery.Graph.RequestHandlers.AzureResourceGraphThrottlingRequestHandler.AvailableRateLimitingCallsAsync(HttpResponseMessage response) in /src/Promitor.Agents.ResourceDiscovery/RequestHandlers/AzureResourceGraphThrottlingRequestHandler.cs:line 52
   at Promitor.Agents.Core.RequestHandlers.ThrottlingRequestHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /src/Promitor.Agents.Core/ThrottlingRequestHandler.cs:line 44
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Management.ResourceGraph.ResourceGraphClient.ResourcesWithHttpMessagesAsync(QueryRequest query, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceGraph.ResourceGraphClientExtensions.ResourcesAsync(IResourceGraphClient operations, QueryRequest query, CancellationToken cancellationToken)
   at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.<>c__DisplayClass15_0.<<QueryAsync>b__0>d.MoveNext() in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.<>c__DisplayClass16_0`1.<<InteractWithAzureResourceGraphAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.InteractWithAzureResourceGraphAsync[TResponse](String queryName, String query, Func`2 interactionFunc, List`1 targetSubscriptions) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 110
   at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.QueryAsync(String queryName, String query, List`1 targetSubscriptions) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 90
   at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.QueryAzureLandscapeAsync(String queryName, String query) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 64
   at Promitor.Agents.ResourceDiscovery.Graph.Repositories.AzureResourceRepository.DiscoverAzureResourceGroupsAsync() in /src/Promitor.Agents.ResourceDiscovery/Repositories/AzureResourceRepository.cs:line 98
   at Promitor.Agents.ResourceDiscovery.Graph.Repositories.CachedAzureResourceRepository.DiscoverAzureResourceGroupsAsync() in /src/Promitor.Agents.ResourceDiscovery/Repositories/CachedAzureResourceRepository.cs:line 76
   at Promitor.Agents.ResourceDiscovery.Scheduling.AzureResourceGroupsDiscoveryBackgroundJob.ExecuteAsync(CancellationToken cancellationToken) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGroupsDiscoveryBackgroundJob.cs:line 33
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 58
   --- End of inner exception stack trace ---
```

### Steps to Reproduce the Problem

1. Use SystemAssignedManagedIdentity
2. Start the resource discovery

### Component

Resource Discovery

### Version

0.5.0

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

### Logs

```shell
example
```

### Platform

Microsoft Azure

**Comment by tomkerkhove** [comment]
Thanks for the PR! Is this one blocking you? (ie. is a new release urgent?)
