### ISSUE TITLE
Exception errors scraping Express Route Gateway metrics for NetworkGateway resource type

### ISSUE THREAD

**Issue by PowerSurj** [tomkerkhove/promitor#1940]
### Report

Scraping Express Route Gateway metrics for `NetworkGateway` resource type (and ExpressRoute Gateway Type) generates Exception errors, even though metrics get successfully scraped.

I only tested below metrics and all of them generate Exceptions.

ExpressRouteGatewayCountOfRoutesLearnedFromPeer
ExpressRouteGatewayCountOfRoutesAdvertisedToPeer
ExpressRouteGatewayCpuUtilization
ExpressRouteGatewayPacketsPerSecond

### Expected Behavior

no Exception error

### Actual Behavior

getting Exception errors, and obviously error reflected in `promitor_scrape_error` scraper metric

### Steps to Reproduce the Problem

You must have Azure Virtual Network Gateway configured of ExpressRoute type.

### Component

Scraper

### Version

2.6.0

### Configuration

Configuration:

```
image:
  tag: "2.6.0"

metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    schedule: "* * * * *"
metrics:
  - name: azure_virtual_network_gateway_express_route_gateway_cpu_utilization
    description: "CPU Utilization of the ExpressRoute Gateway"
    resourceType: NetworkGateway
    azureMetricConfiguration:
      metricName: ExpressRouteGatewayCpuUtilization
      aggregation:
        type: Average
    resourceDiscoveryGroups:
      - name: NetworkGateway
```

### Logs

Exception error example:
```
Failed to scrape resource for metric 'azure_virtual_network_gateways_express_route_gateway_cpu_utilization'
Promitor.Integrations.AzureMonitor.Exceptions.MetricNotFoundException: The metric 'ExpressRouteGatewayCpuUtilization' was not found
   at Promitor.Integrations.AzureMonitor.AzureMonitorClient.QueryMetricAsync(String metricName, String metricDimension, AggregationType aggregationType, TimeSpan aggregationInterval, String resourceId, String metricFilter, Nullable`1 metricLimit) in /src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs:line 78
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 72
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 103
```
Followed by successful found metric event:

```
Found value 1 for metric azure_virtual_network_gateways_express_route_gateway_cpu_utilization with aggregation interval 00:05:00
```

### Platform

Microsoft Azure

**Comment by tomkerkhove** [comment]
Hm odd, I have never been able to test with express route but can you try a more general one? Maybe ExpressRoute needs more information.
