### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by Kamalika-saha** [tomkerkhove/promitor#2432]
### Report

I am trying to use promitor version 2.11.x with the following value file :
`azureAuthentication:
  identity:
    binding: <name>-identity
    id: xxxx
  mode: UserAssignedManagedIdentity
azureMetadata:
  subscriptionId: xx
  tenantId: xx
metricDefaults:
  aggregation:
    interval: "00:02:00"
  scraping:
    schedule: "0 */2 * ? * *"
metrics:
- azureMetricConfiguration:
    aggregation:
      type: Average
    metricName: Size
  description: Size of topic
  name: promitor_azure_service_bus_topic_size
  resourceType: ServiceBusNamespace
  resources:
  - namespace: bus-1
    topicName: recordstopic
    resourceGroupName: DataPartition-rg-<name1>-dp1-xhgyrm
  - namespace: bus-2
    topicName: recordstopic
    resourceGroupName: DataPartition-rg-<name2>-dp2-xhgyrm
`
However it is failing to scrape the metric. The follow is the error message found on looking into kubectl logs : 
`Failed to scrape resource for metric 'demo_queue_size'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.<>c.<EnrichMeasuredMetrics>b__2_0(MeasuredMetric metricValue) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.EnrichMeasuredMetrics(TResourceDefinition resourceDefinition, List`1 dimensionNames, List`1 metricValues) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 71
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 79
has context menu`
Is there any work around to this issue? Am I missing anything in the values file? 
I am prepared the values file according to the latest documentation of Promitor.

### Expected Behavior

It should be able to scrape the required metrics.

### Actual Behavior

However it is failing to scrape the metric. The follow is the error message found on looking into kubectl logs : 
`Failed to scrape resource for metric 'demo_queue_size'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.<>c.<EnrichMeasuredMetrics>b__2_0(MeasuredMetric metricValue) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.EnrichMeasuredMetrics(TResourceDefinition resourceDefinition, List`1 dimensionNames, List`1 metricValues) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 71
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 79
has context menu`

### Steps to Reproduce the Problem

1.
2.
3.
...

### Component

Scraper

### Version

2.11.x

### Configuration

azureAuthentication:
  identity:
    binding: <name>-identity
    id: xxxx
  mode: UserAssignedManagedIdentity
azureMetadata:
  subscriptionId: xx
  tenantId: xx
metricDefaults:
  aggregation:
    interval: "00:02:00"
  scraping:
    schedule: "0 */2 * ? * *"
metrics:
- azureMetricConfiguration:
    aggregation:
      type: Average
    metricName: Size
  description: Size of topic
  name: promitor_azure_service_bus_topic_size
  resourceType: ServiceBusNamespace
  resources:
  - namespace: bus-1
    topicName: recordstopic
    resourceGroupName: DataPartition-rg-<name1>-dp1-xhgyrm
  - namespace: bus-2
    topicName: recordstopic
    resourceGroupName: DataPartition-rg-<name2>-dp2-xhgyrm

### Logs

However it is failing to scrape the metric. The follow is the error message found on looking into kubectl logs : 
`Failed to scrape resource for metric 'demo_queue_size'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.<>c.<EnrichMeasuredMetrics>b__2_0(MeasuredMetric metricValue) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.EnrichMeasuredMetrics(TResourceDefinition resourceDefinition, List`1 dimensionNames, List`1 metricValues) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 71
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 79
has context menu`

### Platform

Microsoft Azure

### Contact Details

kamalikasaha894@gmail.com

**Comment by Kamalika-saha** [comment]
FYI: This same config file seems to be working perfectly fine with promitor verion 2.9.x

**Comment by tomkerkhove** [comment]
> Thank you for opening an issue! We rely on the community to maintain Promitor. ([Learn more](https://github.com/tomkerkhove/promitor/issues/2425))
> 
> Is this something you want to contribute?

Are you willing to contribute a fix?

**Comment by Kamalika-saha** [comment]
From the error message, it seems that the error is coming from the following file  : src/Promitor.Core.Scraping/ResourceTypes/AzureMessagingScraper.cs
 Function:
`protected override List<MeasuredMetric> EnrichMeasuredMetrics(TResourceDefinition resourceDefinition, List<string> dimensionNames, List<MeasuredMetric> metricValues)
        {
            // Change Azure Monitor Dimension name to more representable value
            foreach (var measuredMetric in metricValues.Where(metricValue => metricValue.Dimensions.Any()))
            {
                measuredMetric.Dimensions[0].Name = EntityNameLabel;
            }

            return metricValues;
        }`
We can include a null check in this function. Something like : 
`protected override List<MeasuredMetric> EnrichMeasuredMetrics(TResourceDefinition resourceDefinition, List<string> dimensionNames, List<MeasuredMetric> metricValues)
{
    if (metricValues == null)
    {
        // Handle the case where metricValues is null, if necessary
        return null; // or return an empty list, depending on your requirements
    }

    // Change Azure Monitor Dimension name to a more representable value
    foreach (var measuredMetric in metricValues.Where(metricValue => metricValue.Dimensions.Any()))
    {
        measuredMetric.Dimensions[0].Name = EntityNameLabel;
    }

    return metricValues;
}
`

**Comment by tomkerkhove** [comment]
Are you willing to contribute a fix?

**Comment by rmacian** [comment]
Same error here but for Azure Service Bus metrics
```
[16:42:57 FTL] Failed to scrape resource for metric 'azure_servicebusnamespace_abandonmessage'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.<>c.<EnrichMeasuredMetrics>b__2_0(MeasuredMetric metricValue) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Promitor.Core.Scraping.ResourceTypes.AzureMessagingScraper`1.EnrichMeasuredMetrics(TResourceDefinition resourceDefinition, List`1 dimensionNames, List`1 metricValues) in /src/Promitor.Core.Scraping/AzureMessagingScraper.cs:line 22
   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 71
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 79
```

**Comment by rmacian** [comment]
any update on this ?
